<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rr_mousebot_bringup</name>
  <version>0.0.10</version>
  <description>Launch package for launching mousebot maze solver</description>
  <maintainer email="azzmosphere@gmail.com">aaron</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>launch</depend>
  <depend>nav2_util</depend>
  <depend>rr_motor_controller</depend>
  <depend>rr_gpio_pi4b_pigpio_plugin</depend>
  <depend>rr_bosch_lc_base</depend>
  <depend>nav2_lifecycle_manager</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
